export const tempAsset = [
  // ...
  {
    id: 1,
    assetNumber: "asset2",
    customer_account: "Customer2",
    product: "Product2",
    asset_type: "AssetType2",
    device_name: "Device1",
    manufacturer: "Manufacture1",
    vendor: "Vendor1",
    model: "Model1",
    model_version: "modVersion1",
    serial_number: "Serial1",
    ip_address: "IP1",
    snmp_community_string: "snmp1",
    location: "loc1",
    owner_name: "owner1",
    contracts_start_dt: 2024 - 23 - 21,
    contracts_end_dt: "2024-23-21",
    aggregated_to_: "Aggr1",
    status: "Stat1",
    vendor_account_manager: "venAccM1",
    contact_number: "1486281",
    contact_email: "asudi@gamsf.com",
    website: "www.dasdn.com",
    service_availed: "service1",
    cost: 1248.124,
    cost_frequency: "costFreq1",
    tags: 12,
    notes: "2024-23-21",
    modified_dt: {
      type: 2024 - 23 - 21,
    },
    customer_name: "cust1",
    created_by: "Cust1",
    created_dt: {
      type: "2024-23-21",
    },
  },
  {
    id: 2,
    assetNumber: "asset1",
    customer_account: "Customer1",
    product: "Product1",
    asset_type: "AssetType1",
    device_name: "Device1",
    manufacturer: "Manufacture1",
    vendor: "Vendor1",
    model: "Model1",
    model_version: "modVersion1",
    serial_number: "Serial1",
    ip_address: "IP1",
    snmp_community_string: "snmp1",
    location: "loc1",
    owner_name: "owner1",
    contracts_start_dt: "2024-23-21",
    contracts_end_dt: "2024-23-21",
    aggregated_to_: "Aggr1",
    status: "Stat1",
    vendor_account_manager: "venAccM1",
    contact_number: "1486281",
    contact_email: "asudi@gamsf.com",
    website: "www.dasdn.com",
    service_availed: "service1",
    cost: 1248.124,
    cost_frequency: "costFreq1",
    tags: 12,
    notes: "2024-23-21",
    modified_dt: {
      type: 2024 - 23 - 21,
    },
    customer_name: "cust1",
    created_by: "Cust1",
    created_dt: {
      type: "2024-23-21",
    },
  },
  {
    id: 3,
    assetNumber: "asset1",
    customer_account: "Customer1",
    product: "Product1",
    asset_type: "AssetType1",
    device_name: "Device1",
    manufacturer: "Manufacture1",
    vendor: "Vendor1",
    model: "Model1",
    model_version: "modVersion1",
    serial_number: "Serial1",
    ip_address: "IP1",
    snmp_community_string: "snmp1",
    location: "loc1",
    owner_name: "owner1",
    contracts_start_dt: "2024-23-21",
    contracts_end_dt: "2024-23-21",
    aggregated_to_: "Aggr1",
    status: "Stat1",
    vendor_account_manager: "venAccM1",
    contact_number: "1486281",
    contact_email: "asudi@gamsf.com",
    website: "www.dasdn.com",
    service_availed: "service1",
    cost: 1248.124,
    cost_frequency: "costFreq1",
    tags: 12,
    notes: "2024-23-21",
    modified_dt: {
      type: 2024 - 23 - 21,
    },
    customer_name: "cust1",
    created_by: "Cust1",
    created_dt: {
      type: "2024-23-21",
    },
  },
  {
    id: 4,
    assetNumber: "asset1",
    customer_account: "Customer1",
    product: "Product1",
    asset_type: "AssetType1",
    device_name: "Device1",
    manufacturer: "Manufacture1",
    vendor: "Vendor1",
    model: "Model1",
    model_version: "modVersion1",
    serial_number: "Serial1",
    ip_address: "IP1",
    snmp_community_string: "snmp1",
    location: "loc1",
    owner_name: "owner1",
    contracts_start_dt: "2024-23-21",
    contracts_end_dt: "2024-23-21",
    aggregated_to_: "Aggr1",
    status: "Stat1",
    vendor_account_manager: "venAccM1",
    contact_number: "1486281",
    contact_email: "asudi@gamsf.com",
    website: "www.dasdn.com",
    service_availed: "service1",
    cost: 1248.124,
    cost_frequency: "costFreq1",
    tags: 12,
    notes: "2024-23-21",
    modified_dt: {
      type: 2024 - 23 - 21,
    },
    customer_name: "cust1",
    created_by: "Cust1",
    created_dt: {
      type: "2024-23-21",
    },
  },
  {
    id: 5,
    assetNumber: "asset1",
    customer_account: "Customer1",
    product: "Product1",
    asset_type: "AssetType1",
    device_name: "Device1",
    manufacturer: "Manufacture1",
    vendor: "Vendor1",
    model: "Model1",
    model_version: "modVersion1",
    serial_number: "Serial1",
    ip_address: "IP1",
    snmp_community_string: "snmp1",
    location: "loc1",
    owner_name: "owner1",
    contracts_start_dt: "2024-23-21",
    contracts_end_dt: "2024-23-21",
    aggregated_to_: "Aggr1",
    status: "Stat1",
    vendor_account_manager: "venAccM1",
    contact_number: "1486281",
    contact_email: "asudi@gamsf.com",
    website: "www.dasdn.com",
    service_availed: "service1",
    cost: 1248.124,
    cost_frequency: "costFreq1",
    tags: 12,
    notes: "2024-23-21",
    modified_dt: {
      type: 2024 - 23 - 21,
    },
    customer_name: "cust1",
    created_by: "Cust1",
    created_dt: {
      type: "2024-23-21",
    },
  },
  {
    id: 6,
    assetNumber: "asset1",
    customer_account: "Customer1",
    product: "Product1",
    asset_type: "AssetType1",
    device_name: "Device1",
    manufacturer: "Manufacture1",
    vendor: "Vendor1",
    model: "Model1",
    model_version: "modVersion1",
    serial_number: "Serial1",
    ip_address: "IP1",
    snmp_community_string: "snmp1",
    location: "loc1",
    owner_name: "owner1",
    contracts_start_dt: "2024-23-21",
    contracts_end_dt: "2024-23-21",
    aggregated_to_: "Aggr1",
    status: "Stat1",
    vendor_account_manager: "venAccM1",
    contact_number: "1486281",
    contact_email: "asudi@gamsf.com",
    website: "www.dasdn.com",
    service_availed: "service1",
    cost: 1248.124,
    cost_frequency: "costFreq1",
    tags: 12,
    notes: "2024-23-21",
    modified_dt: {
      type: 2024 - 23 - 21,
    },
    customer_name: "cust1",
    created_by: "Cust1",
    created_dt: {
      type: "2024-23-21",
    },
  },
  {
    id: 7,
    assetNumber: "asset1",
    customer_account: "Customer1",
    product: "Product1",
    asset_type: "AssetType1",
    device_name: "Device1",
    manufacturer: "Manufacture1",
    vendor: "Vendor1",
    model: "Model1",
    model_version: "modVersion1",
    serial_number: "Serial1",
    ip_address: "IP1",
    snmp_community_string: "snmp1",
    location: "loc1",
    owner_name: "owner1",
    contracts_start_dt: "2024-23-21",
    contracts_end_dt: "2024-23-21",
    aggregated_to_: "Aggr1",
    status: "Stat1",
    vendor_account_manager: "venAccM1",
    contact_number: "1486281",
    contact_email: "asudi@gamsf.com",
    website: "www.dasdn.com",
    service_availed: "service1",
    cost: 1248.124,
    cost_frequency: "costFreq1",
    tags: 12,
    notes: "2024-23-21",
    modified_dt: {
      type: 2024 - 23 - 21,
    },
    customer_name: "cust1",
    created_by: "Cust1",
    created_dt: {
      type: "2024-23-21",
    },
  },
];
